version: '2'

services:
  api: # Node.js App
    container_name: node-api-redis
    build: .
    ports:
      - "4000:4000" # Expose API port
    environment: # Set ENV vars
     - REDIS_URL=redis://redis-app
     - PORT=3000
    volumes: # Attach local book data directory
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
  cache:
    container_name: redis-app
    image: redis
    expose:
      - 6379